// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[PrimaryKey("PlayerId", "AutomationFeature", "AutomationRuleId")]
public partial class AutomationActionState
{
    [Key]
    public Guid PlayerId { get; set; }

    [Key]
    public int AutomationFeature { get; set; }

    [Key]
    [StringLength(128)]
    public string AutomationRuleId { get; set; } = null!;

    public DateTime LastUpdatedUtc { get; set; }

    [ForeignKey("PlayerId")]
    [InverseProperty("AutomationActionStates")]
    public virtual Player Player { get; set; } = null!;
}