// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("BanFileMonitorId", Name = "IX_BanFileMonitorId", IsUnique = true)]
[Index("GameServerId", Name = "IX_BanFileMonitors_GameServerId")]
public partial class BanFileMonitor
{
    [Key]
    public Guid BanFileMonitorId { get; set; }

    public Guid GameServerId { get; set; }

    public string FilePath { get; set; } = null!;

    public long? RemoteFileSize { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastSync { get; set; }

    [Precision(3)]
    public DateTime? LastCheckUtc { get; set; }

    [StringLength(20)]
    public string? LastCheckResult { get; set; }

    [StringLength(500)]
    public string? LastCheckErrorMessage { get; set; }

    [StringLength(500)]
    public string? RemoteFilePath { get; set; }

    [StringLength(100)]
    public string? ResolvedForMod { get; set; }

    [Precision(3)]
    public DateTime? LastImportUtc { get; set; }

    public int? LastImportBanCount { get; set; }

    [StringLength(1000)]
    public string? LastImportSampleNames { get; set; }

    [Precision(3)]
    public DateTime? LastPushUtc { get; set; }

    [Column("LastPushedETag")]
    [StringLength(100)]
    public string? LastPushedEtag { get; set; }

    public long? LastPushedSize { get; set; }

    [Column("LastCentralBlobETag")]
    [StringLength(100)]
    public string? LastCentralBlobEtag { get; set; }

    [Precision(3)]
    public DateTime? LastCentralBlobUtc { get; set; }

    public int ConsecutiveFailureCount { get; set; }

    public int? RemoteTotalLineCount { get; set; }

    public int? RemoteUntaggedCount { get; set; }

    public int? RemoteBanSyncCount { get; set; }

    public int? RemoteExternalCount { get; set; }

    [ForeignKey("GameServerId")]
    [InverseProperty("BanFileMonitors")]
    public virtual GameServer GameServer { get; set; } = null!;
}