// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Table("CentralBanFileStatus")]
public partial class CentralBanFileStatus
{
    [Key]
    public int GameType { get; set; }

    [Precision(3)]
    public DateTime? BlobLastRegeneratedUtc { get; set; }

    [Column("BlobETag")]
    [StringLength(100)]
    public string? BlobEtag { get; set; }

    public long? BlobSizeBytes { get; set; }

    public int? TotalLineCount { get; set; }

    public int? BanSyncLineCount { get; set; }

    public int? ExternalLineCount { get; set; }

    [Precision(3)]
    public DateTime? ExternalSourceLastModifiedUtc { get; set; }

    public int? LastRegenerationDurationMs { get; set; }

    public string? LastRegenerationError { get; set; }

    [StringLength(128)]
    public string? ActiveBanSetHash { get; set; }

    [Precision(3)]
    public DateTime LastUpdatedUtc { get; set; }
}