// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("PlayerId", "GameServerId", Name = "IX_ChatMessages")]
[Index("GameServerId", Name = "IX_GameServerId")]
[Index("PlayerId", Name = "IX_PlayerId")]
[Index("Timestamp", Name = "IX_Timestamp")]
public partial class ChatMessage
{
    [Key]
    public Guid ChatMessageId { get; set; }

    public Guid GameServerId { get; set; }

    public Guid PlayerId { get; set; }

    public string Username { get; set; } = null!;

    public int ChatType { get; set; }

    public string Message { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime Timestamp { get; set; }

    public bool Locked { get; set; }

    [ForeignKey("GameServerId")]
    [InverseProperty("ChatMessages")]
    public virtual GameServer GameServer { get; set; } = null!;

    [ForeignKey("PlayerId")]
    [InverseProperty("ChatMessages")]
    public virtual Player Player { get; set; } = null!;
}