// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("CodeHash", "IsActive", "ExpiresAtUtc", Name = "IX_ConnectedPlayerActivationCodes_CodeHash_IsActive_ExpiresAtUtc")]
[Index("ConnectedPlayerActivationCodeId", Name = "IX_ConnectedPlayerActivationCodes_ConnectedPlayerActivationCodeId", IsUnique = true)]
[Index("UserProfileId", "IsActive", "ExpiresAtUtc", Name = "IX_ConnectedPlayerActivationCodes_UserProfileId_IsActive_ExpiresAtUtc")]
public partial class ConnectedPlayerActivationCode
{
    [Key]
    public Guid ConnectedPlayerActivationCodeId { get; set; }

    public Guid UserProfileId { get; set; }

    [StringLength(6)]
    public string Code { get; set; } = null!;

    [StringLength(256)]
    public string CodeHash { get; set; } = null!;

    [Precision(3)]
    public DateTime ExpiresAtUtc { get; set; }

    public int AttemptCount { get; set; }

    public int MaxAttempts { get; set; }

    public bool IsActive { get; set; }

    [Precision(3)]
    public DateTime ActivatedAtUtc { get; set; }

    [StringLength(32)]
    public string ActivatedBy { get; set; } = null!;

    [Precision(3)]
    public DateTime? InvalidatedAtUtc { get; set; }

    [Precision(3)]
    public DateTime? ConsumedAtUtc { get; set; }

    [ForeignKey("UserProfileId")]
    [InverseProperty("ConnectedPlayerActivationCode")]
    public virtual UserProfile UserProfile { get; set; } = null!;
}