// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("ConnectedPlayerProfileId", Name = "IX_ConnectedPlayerProfiles_ConnectedPlayerProfileId", IsUnique = true)]
public partial class ConnectedPlayerProfile
{
    [Key]
    public Guid ConnectedPlayerProfileId { get; set; }

    public Guid PlayerId { get; set; }

    public Guid UserProfileId { get; set; }

    [StringLength(32)]
    public string LinkMethod { get; set; } = null!;

    [Precision(3)]
    public DateTime LinkedAtUtc { get; set; }

    public Guid? LinkedByUserProfileId { get; set; }

    [Precision(3)]
    public DateTime? UnlinkedAtUtc { get; set; }

    public Guid? UnlinkedByUserProfileId { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("LinkedByUserProfileId")]
    [InverseProperty("ConnectedPlayerProfileLinkedByUserProfiles")]
    public virtual UserProfile? LinkedByUserProfile { get; set; }

    [ForeignKey("PlayerId")]
    [InverseProperty("ConnectedPlayerProfiles")]
    public virtual Player Player { get; set; } = null!;

    [ForeignKey("UnlinkedByUserProfileId")]
    [InverseProperty("ConnectedPlayerProfileUnlinkedByUserProfiles")]
    public virtual UserProfile? UnlinkedByUserProfile { get; set; }

    [ForeignKey("UserProfileId")]
    [InverseProperty("ConnectedPlayerProfileUserProfiles")]
    public virtual UserProfile UserProfile { get; set; } = null!;
}