// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("ConnectedPlayerRegistrationTokenId", Name = "IX_ConnectedPlayerRegistrationTokens_ConnectedPlayerRegistrationTokenId", IsUnique = true)]
[Index("PlayerId", "IsActive", "ExpiresAtUtc", Name = "IX_ConnectedPlayerRegistrationTokens_PlayerId_IsActive_ExpiresAtUtc")]
public partial class ConnectedPlayerRegistrationToken
{
    [Key]
    public Guid ConnectedPlayerRegistrationTokenId { get; set; }

    public Guid PlayerId { get; set; }

    [StringLength(256)]
    public string TokenHash { get; set; } = null!;

    [Precision(3)]
    public DateTime ExpiresAtUtc { get; set; }

    public int AttemptCount { get; set; }

    public int MaxAttempts { get; set; }

    public bool IsActive { get; set; }

    [Precision(3)]
    public DateTime IssuedAtUtc { get; set; }

    [StringLength(32)]
    public string IssuedBy { get; set; } = null!;

    [Precision(3)]
    public DateTime? InvalidatedAtUtc { get; set; }

    [Precision(3)]
    public DateTime? VerifiedAtUtc { get; set; }

    [ForeignKey("PlayerId")]
    [InverseProperty("ConnectedPlayerRegistrationTokens")]
    public virtual Player Player { get; set; } = null!;
}