// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[PrimaryKey("GameServerId", "Namespace")]
public partial class GameServerConfiguration
{
    [Key]
    public Guid GameServerId { get; set; }

    [Key]
    [StringLength(128)]
    public string Namespace { get; set; } = null!;

    public string Configuration { get; set; } = null!;

    public DateTime LastModifiedUtc { get; set; }

    [ForeignKey("GameServerId")]
    [InverseProperty("GameServerConfigurations")]
    public virtual GameServer GameServer { get; set; } = null!;
}