// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("MapId", Name = "IX_MapFlags_MapId")]
public partial class MapFlag
{
    [Key]
    public Guid MapFlagId { get; set; }

    public Guid MapId { get; set; }

    public int FlagType { get; set; }

    public string? Reason { get; set; }

    [StringLength(256)]
    public string? ReportedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    [ForeignKey("MapId")]
    [InverseProperty("MapFlags")]
    public virtual Map Map { get; set; } = null!;
}