// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("MapId", Name = "IX_MapId")]
[Index("MapPackId", Name = "IX_MapPackId")]
public partial class MapPackMap
{
    [Key]
    public Guid MapPackMapId { get; set; }

    public Guid? MapPackId { get; set; }

    public Guid MapId { get; set; }

    [ForeignKey("MapId")]
    [InverseProperty("MapPackMaps")]
    public virtual Map Map { get; set; } = null!;

    [ForeignKey("MapPackId")]
    [InverseProperty("MapPackMaps")]
    public virtual MapPack? MapPack { get; set; }
}