// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("MapRotationServerAssignmentId", Name = "IX_MapRotationAssignmentOperations_AssignmentId")]
public partial class MapRotationAssignmentOperation
{
    [Key]
    public Guid MapRotationAssignmentOperationId { get; set; }

    public Guid MapRotationServerAssignmentId { get; set; }

    public int OperationType { get; set; }

    public int Status { get; set; }

    [StringLength(256)]
    public string? DurableFunctionInstanceId { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public string? Error { get; set; }

    [ForeignKey("MapRotationServerAssignmentId")]
    [InverseProperty("MapRotationAssignmentOperations")]
    public virtual MapRotationServerAssignment MapRotationServerAssignment { get; set; } = null!;
}