// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("GameType", Name = "IX_MapRotations_GameType")]
[Index("Status", Name = "IX_MapRotations_Status")]
public partial class MapRotation
{
    [Key]
    public Guid MapRotationId { get; set; }

    public int GameType { get; set; }

    [StringLength(256)]
    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    [StringLength(50)]
    public string GameMode { get; set; } = null!;

    public int Status { get; set; }

    [StringLength(50)]
    public string? Category { get; set; }

    public int? SequenceOrder { get; set; }

    public int Version { get; set; }

    [StringLength(64)]
    public string? ContentHash { get; set; }

    public Guid? CreatedByUserId { get; set; }

    public Guid? LastModifiedByUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    [ForeignKey("CreatedByUserId")]
    [InverseProperty("MapRotationCreatedByUsers")]
    public virtual UserProfile? CreatedByUser { get; set; }

    [ForeignKey("LastModifiedByUserId")]
    [InverseProperty("MapRotationLastModifiedByUsers")]
    public virtual UserProfile? LastModifiedByUser { get; set; }

    [InverseProperty("MapRotation")]
    public virtual ICollection<MapRotationMap> MapRotationMaps { get; set; } = new List<MapRotationMap>();

    [InverseProperty("MapRotation")]
    public virtual ICollection<MapRotationServerAssignment> MapRotationServerAssignments { get; set; } = new List<MapRotationServerAssignment>();
}