// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("MapId", Name = "IX_MapRotationMaps_MapId")]
[Index("MapRotationId", Name = "IX_MapRotationMaps_MapRotationId")]
[Index("MapRotationId", "MapId", Name = "UQ_MapRotationMaps_Rotation_Map", IsUnique = true)]
[Index("MapRotationId", "SortOrder", Name = "UQ_MapRotationMaps_Rotation_SortOrder", IsUnique = true)]
public partial class MapRotationMap
{
    [Key]
    public Guid MapRotationMapId { get; set; }

    public Guid MapRotationId { get; set; }

    public Guid MapId { get; set; }

    public int SortOrder { get; set; }

    [ForeignKey("MapId")]
    [InverseProperty("MapRotationMaps")]
    public virtual Map Map { get; set; } = null!;

    [ForeignKey("MapRotationId")]
    [InverseProperty("MapRotationMaps")]
    public virtual MapRotation MapRotation { get; set; } = null!;
}