// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("DeploymentState", Name = "IX_MapRotationServerAssignments_DeploymentState")]
[Index("GameServerId", Name = "IX_MapRotationServerAssignments_GameServerId")]
[Index("MapRotationId", Name = "IX_MapRotationServerAssignments_MapRotationId")]
public partial class MapRotationServerAssignment
{
    [Key]
    public Guid MapRotationServerAssignmentId { get; set; }

    public Guid MapRotationId { get; set; }

    public Guid GameServerId { get; set; }

    public int DeploymentState { get; set; }

    public int ActivationState { get; set; }

    public int? DeployedVersion { get; set; }

    public int? ActivatedVersion { get; set; }

    [StringLength(256)]
    public string? ConfigFilePath { get; set; }

    [StringLength(256)]
    public string? ConfigVariableName { get; set; }

    public string? LastError { get; set; }

    public DateTime? LastErrorAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? UnassignedAt { get; set; }

    [ForeignKey("GameServerId")]
    [InverseProperty("MapRotationServerAssignments")]
    public virtual GameServer GameServer { get; set; } = null!;

    [ForeignKey("MapRotationId")]
    [InverseProperty("MapRotationServerAssignments")]
    public virtual MapRotation MapRotation { get; set; } = null!;

    [InverseProperty("MapRotationServerAssignment")]
    public virtual ICollection<MapRotationAssignmentOperation> MapRotationAssignmentOperations { get; set; } = new List<MapRotationAssignmentOperation>();
}