// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("GameType", Name = "IX_MapRotations_GameType")]
public partial class MapRotation
{
    [Key]
    public Guid MapRotationId { get; set; }

    public int GameType { get; set; }

    [StringLength(256)]
    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    [StringLength(50)]
    public string GameMode { get; set; } = null!;

    public int Version { get; set; }

    [StringLength(64)]
    public string? ContentHash { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    [InverseProperty("MapRotation")]
    public virtual ICollection<MapRotationMap> MapRotationMaps { get; set; } = new List<MapRotationMap>();

    [InverseProperty("MapRotation")]
    public virtual ICollection<MapRotationServerAssignment> MapRotationServerAssignments { get; set; } = new List<MapRotationServerAssignment>();
}