// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("CreatedAt", Name = "IX_Notifications_CreatedAt")]
[Index("NotificationTypeId", Name = "IX_Notifications_NotificationTypeId")]
[Index("UserProfileId", Name = "IX_Notifications_UserProfileId")]
[Index("UserProfileId", "IsRead", Name = "IX_Notifications_UserProfileId_IsRead")]
public partial class Notification
{
    [Key]
    public Guid NotificationId { get; set; }

    public Guid UserProfileId { get; set; }

    [StringLength(50)]
    public string NotificationTypeId { get; set; } = null!;

    [StringLength(256)]
    public string Title { get; set; } = null!;

    public string Message { get; set; } = null!;

    [StringLength(512)]
    public string? ActionUrl { get; set; }

    public string? MetadataJson { get; set; }

    public bool IsRead { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReadAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public bool EmailSent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EmailSentAt { get; set; }

    [ForeignKey("NotificationTypeId")]
    [InverseProperty("Notifications")]
    public virtual NotificationType NotificationType { get; set; } = null!;

    [ForeignKey("UserProfileId")]
    [InverseProperty("Notifications")]
    public virtual UserProfile UserProfile { get; set; } = null!;
}