// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("UserProfileId", "NotificationTypeId", Name = "IX_NotificationPreferences_UserProfileId_NotificationTypeId", IsUnique = true)]
public partial class NotificationPreference
{
    [Key]
    public Guid NotificationPreferenceId { get; set; }

    public Guid UserProfileId { get; set; }

    [StringLength(50)]
    public string NotificationTypeId { get; set; } = null!;

    public bool InSiteEnabled { get; set; }

    public bool EmailEnabled { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastModified { get; set; }

    [ForeignKey("UserProfileId")]
    [InverseProperty("NotificationPreferences")]
    public virtual UserProfile UserProfile { get; set; } = null!;

    [ForeignKey("NotificationTypeId")]
    [InverseProperty("NotificationPreferences")]
    public virtual NotificationType NotificationType { get; set; } = null!;
}
