// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

public partial class NotificationType
{
    [Key]
    [StringLength(50)]
    public string NotificationTypeId { get; set; } = null!;

    [StringLength(128)]
    public string DisplayName { get; set; } = null!;

    [StringLength(512)]
    public string Description { get; set; } = null!;

    [StringLength(50)]
    public string Category { get; set; } = null!;

    public bool SupportsInSite { get; set; }

    public bool SupportsEmail { get; set; }

    [StringLength(256)]
    public string DefaultChannels { get; set; } = null!;

    public bool IsEnabled { get; set; }

    public int SortOrder { get; set; }

    [InverseProperty("NotificationType")]
    public virtual ICollection<NotificationPreference> NotificationPreferences { get; set; } = [];

    [InverseProperty("NotificationType")]
    public virtual ICollection<Notification> Notifications { get; set; } = [];
}
