// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("GameServerId", "RequestedAtUtc", Name = "IX_ScreenshotPendingRequests_GameServerId_RequestedAtUtc", IsDescending = new[] { false, true })]
public partial class ScreenshotPendingRequest
{
    [Key]
    public Guid ScreenshotPendingRequestId { get; set; }

    public Guid GameServerId { get; set; }

    [StringLength(64)]
    public string PlayerIdentifier { get; set; } = null!;

    [StringLength(128)]
    public string? PlayerName { get; set; }

    [StringLength(64)]
    public string? CorrelationKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RequestedAtUtc { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpiresAtUtc { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ConsumedAtUtc { get; set; }

    [StringLength(128)]
    public string? CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedUtc { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdatedUtc { get; set; }

    [ForeignKey("GameServerId")]
    [InverseProperty("ScreenshotPendingRequests")]
    public virtual GameServer GameServer { get; set; } = null!;
}