// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

[Index("CapturedUtc", Name = "IX_Screenshots_CapturedUtc", AllDescending = true)]
[Index("GameServerId", "CapturedUtc", "ScreenshotId", Name = "IX_Screenshots_GameServerId_CapturedUtc", IsDescending = new[] { false, true, true })]
[Index("GameServerId", "Fingerprint", Name = "IX_Screenshots_GameServerId_Fingerprint", IsUnique = true)]
[Index("GameServerId", "PlayerIdentifier", "CapturedUtc", Name = "IX_Screenshots_GameServerId_PlayerIdentifier_CapturedUtc", IsDescending = new[] { false, false, true })]
public partial class Screenshot
{
    [Key]
    public Guid ScreenshotId { get; set; }

    public Guid GameServerId { get; set; }

    public int GameType { get; set; }

    [StringLength(64)]
    public string PlayerIdentifier { get; set; } = null!;

    [StringLength(128)]
    public string? PlayerName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CapturedUtc { get; set; }

    [StringLength(128)]
    public string BlobContainer { get; set; } = null!;

    [StringLength(1024)]
    public string BlobName { get; set; } = null!;

    [StringLength(2048)]
    public string? BlobUri { get; set; }

    [StringLength(128)]
    public string ContentType { get; set; } = null!;

    public long SizeBytes { get; set; }

    [Column("ETag")]
    [StringLength(128)]
    public string? Etag { get; set; }

    [StringLength(64)]
    public string Source { get; set; } = null!;

    [StringLength(64)]
    public string Fingerprint { get; set; } = null!;

    [StringLength(260)]
    public string SourceFileName { get; set; } = null!;

    public long SourceSizeBytes { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SourceLastWriteUtc { get; set; }

    public bool Deleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedUtc { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedUtc { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdatedUtc { get; set; }

    [ForeignKey("GameServerId")]
    [InverseProperty("Screenshots")]
    public virtual GameServer GameServer { get; set; } = null!;
}