// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.Repository.DataLib;

public partial class Tag
{
    [Key]
    public Guid TagId { get; set; }

    [StringLength(60)]
    public string Name { get; set; } = null!;

    [StringLength(255)]
    public string? Description { get; set; }

    public bool UserDefined { get; set; }

    [StringLength(255)]
    public string? TagHtml { get; set; }

    [InverseProperty("Tag")]
    public virtual ICollection<PlayerTag> PlayerTags { get; set; } = [];
}