name: 'Setup OpenAPI Specs'
description: 'Downloads OpenAPI specs artifact to the root directory'
inputs:
  artifact-name:
    description: 'Name of the artifact containing OpenAPI specs'
    required: false
    default: 'openapi-specs'

runs:
  using: 'composite'
  steps:
    - name: Download OpenAPI Specs
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: .

    - name: Debug - Show Directory Contents
      shell: bash
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "OpenAPI spec files:"
        ls -la *.json 2>/dev/null || echo "No JSON files found"
