// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib;

[Index("MapId", Name = "IX_MapId")]
public partial class MapPackMap
{
    [Key]
    public Guid MapPackMapId { get; set; }

    public Guid MapId { get; set; }

    [ForeignKey("MapId")]
    [InverseProperty("MapPackMaps")]
    public virtual Map Map { get; set; }
}