// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib;

[Index("PlayerId", Name = "IX_PlayerId")]
[Index("PlayerTagId", Name = "IX_PlayerTagId", IsUnique = true)]
public partial class PlayerTag
{
    [Key]
    public Guid PlayerTagId { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? TagId { get; set; }

    public Guid? UserProfileId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Assigned { get; set; }

    [ForeignKey("PlayerId")]
    [InverseProperty("PlayerTags")]
    public virtual Player? Player { get; set; }

    [ForeignKey("TagId")]
    [InverseProperty("PlayerTags")]
    public virtual Tag? Tag { get; set; }

    [ForeignKey("UserProfileId")]
    [InverseProperty("PlayerTags")]
    public virtual UserProfile? UserProfile { get; set; }
}