// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib;

[Index("CreatedByUserProfileId", Name = "IX_CreatedByUserProfileId")]
[Index("PlayerId", Name = "IX_PlayerId")]
[Index("ProtectedNameId", Name = "IX_ProtectedNameId", IsUnique = true)]
public partial class ProtectedName
{
    [Key]
    public Guid ProtectedNameId { get; set; }

    public Guid? PlayerId { get; set; }

    [StringLength(60)]
    public string? Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    public Guid? CreatedByUserProfileId { get; set; }

    [ForeignKey("CreatedByUserProfileId")]
    [InverseProperty("ProtectedNames")]
    public virtual UserProfile? CreatedByUserProfile { get; set; }

    [ForeignKey("PlayerId")]
    [InverseProperty("ProtectedNames")]
    public virtual Player? Player { get; set; }
}