// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib;

[Index("UserProfileId", Name = "IX_UserProfileId", IsUnique = true)]
public partial class UserProfile
{
    [Key]
    public Guid UserProfileId { get; set; }

    [StringLength(50)]
    public string? IdentityOid { get; set; }

    [StringLength(50)]
    public string? XtremeIdiotsForumId { get; set; }

    [StringLength(50)]
    public string? DemoAuthKey { get; set; }

    [StringLength(128)]
    public string? DisplayName { get; set; }

    [StringLength(128)]
    public string? FormattedName { get; set; }

    [StringLength(128)]
    public string? PrimaryGroup { get; set; }

    [StringLength(128)]
    public string? Email { get; set; }

    public string? PhotoUrl { get; set; }

    public string? ProfileUrl { get; set; }

    [StringLength(50)]
    public string? TimeZone { get; set; }

    [InverseProperty("UserProfile")]
    public virtual ICollection<AdminAction> AdminActions { get; set; } = new List<AdminAction>();

    [InverseProperty("UserProfile")]
    public virtual ICollection<Demo> Demos { get; set; } = new List<Demo>();

    [InverseProperty("UserProfile")]
    public virtual ICollection<PlayerTag> PlayerTags { get; set; } = new List<PlayerTag>();

    [InverseProperty("CreatedByUserProfile")]
    public virtual ICollection<ProtectedName> ProtectedNames { get; set; } = new List<ProtectedName>();

    [InverseProperty("AdminUserProfile")]
    public virtual ICollection<Report> ReportAdminUserProfiles { get; set; } = new List<Report>();

    [InverseProperty("UserProfile")]
    public virtual ICollection<Report> ReportUserProfiles { get; set; } = new List<Report>();

    [InverseProperty("UserProfile")]
    public virtual ICollection<UserProfileClaim> UserProfileClaims { get; set; } = new List<UserProfileClaim>();
}