name: "dotnet-ci"

inputs:
  dotnet-version:
    description: "The version of .NET to use"
    required: true
    default: "7.0.x"
  src-folder:
    description: "The folder containing the .NET projects"
    required: true
    default: "src"
  
runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup Package Cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore Dependencies
      run: |
        cd ${{ inputs.src-folder }}
        dotnet restore
      
    - name: Build
      run: |
        cd ${{ inputs.src-folder }}
        dotnet build --no-restore
      
    - name: Test
      run: |
        cd ${{ inputs.src-folder }}
        dotnet test --no-build --verbosity normal --filter FullyQualifiedName!~IntegrationTests
