# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet CI

on:
  #push:
  #  branches: [ "*" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: dotnet CI
      uses: "./.github/templates/dotnet-ci" 
      with:
        dotnet-version: 7.0.x
        src-folder: "src"
