name: Feature Development

on:
  workflow_dispatch:
  push:
    branches-ignore: [ "main" ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  dotnet-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: dotnet CI
      uses: "./.github/templates/dotnet-ci" 
      with:
        dotnet-version: 7.0.x
        src-folder: "src"

  terraform-plan-1:
    name: Terraform Plan
    environment: DevelopmentIaCPlan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: terraform-plan
        uses: frasermolyneux/actions/terraform-plan@main
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/dev.tfvars"
          terraform-backend-file: "backends/dev.backend.hcl"
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - id: foo
        uses: frasermolyneux/actions/hello-world-composite-action@main
        with:
          who-to-greet: 'Mona the Octocat'

  #terraform-plan-2:
  #  name: Terraform Plan
  #  uses: "frasermolyneux/actions/.github/workflows/terraform-plan.yml@main"
  #  needs: ["terraform-plan-1"]
  #  with: 
  #    environment: "DevelopmentIaCPlan"
  #    terraform-folder: "terraform"
  #    terraform-var-file: "tfvars/dev.tfvars"
  #    terraform-backend-file: "backends/dev.backend.hcl"
  #  secrets: inherit
