name: Route To Production

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform-prereq-dev:
    environment: Development

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'Az CLI Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Create Storage Account
      run: |
        az group create --location "uksouth" --name "rg-portal-repository-tf-dev-uksouth"
        az storage account create --name "saptlrepotfdev" --resource-group "rg-portal-repository-tf-dev-uksouth" --location "uksouth" --sku "Standard_LRS"
        az storage container create --name "terraform" --account-name "saptlrepotfdev"

  terraform-prereq-prd:
    environment: Production
    needs: ["terraform-prereq-dev"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'Az CLI Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Create Storage Account
      run: |
        az group create --location "uksouth" --name "rg-portal-repository-tf-prd-uksouth"
        az storage account create --name "saptlrepotfprd" --resource-group "rg-portal-repository-tf-prd-uksouth" --location "uksouth" --sku "Standard_LRS"
        az storage container create --name "terraform" --account-name "saptlrepotfprd"
